name: Android CI test
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "README.md"
      - "README_en.md"
  pull_request:
    paths-ignore:
      - "README.md"
      - "README_en.md"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Build with Gradle
        run: |
          chmod 777 ./gradlew 
          ./gradlew :inrt:assemble 
          ./gradlew :app:assembleCommon
      
      - uses: Tlaster/android-sign@v1.2.2
        name: Sign app APK
        with:
          releaseDirectory: |
            app/build/outputs/apk/common/release
          signingKeyBase64: ${{ secrets.ASIGNING_KEY }}
          output: build/app/signed
          alias: ${{ secrets.AALIAS }}
          keyStorePassword: ${{ secrets.AKEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.AKEY_PASSWORD }}
        env: 
          BUILD_TOOLS_VERSION: "34.0.0"  
     
      - name: upload v8a apk
        uses: actions/upload-artifact@v3
        with:
          name: v8a
          path: build/app/signed/app-common-arm64-v8a-*.apk
       
      - name: upload v7a apk
        uses: actions/upload-artifact@v3
        with: 
          name: v7a
          path: build/app/signed/app-common-armeabi-v7a-*.apk
    
      - name: upload universal apk
        uses: actions/upload-artifact@v3
        with: 
          name: universal
          path: build/app/signed/app-common-universal-*.apk
