name: Android CI test
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "README.md"
      - "README_en.md"
  pull_request:
    paths-ignore:
      - "README.md"
      - "README_en.md"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Build with Gradle
        run: |
          chmod 777 ./gradlew 
          ./gradlew :inrt:assemble 
          ./gradlew :app:assembleCommon
        
      - name: upload v8a apk
        uses: actions/upload-artifact@v3
        with:
          name: v8(no signing)
          path: app/build/outputs/apk/common/release/app-common-arm64-v8a-*.apk
       
      - name: upload v7a apk
        uses: actions/upload-artifact@v3
        with: 
          name: v7(no signing)
          path: app/build/outputs/apk/common/release/app-common-armeabi-v7a-*.apk
