name: Android CI build
permissions:
  contents: write
on:
  workflow_dispatch:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set output
        id: vars
        run: |
          echo "short_ref=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - name: checkout
        id: check
        uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build inrt template
        run: |
          chmod 777 ./gradlew
          ./gradlew app:buildTemplateApp
      - name: Build App
        run: |
          ./gradlew app:assembleCommon
      - uses: Tlaster/android-sign@v1.2.2
        name: Sign app APK
        with:
          releaseDirectory: |
            app/build/outputs/apk/common/release
          signingKeyBase64: ${{ secrets.ASIGNING_KEY }}
          output: build/app/signed
          alias: ${{ secrets.AALIAS }}
          keyStorePassword: ${{ secrets.AKEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.AKEY_PASSWORD }}
        env: 
          BUILD_TOOLS_VERSION: "34.0.0"
      - name: rename apk
        run: |
          cd build/app/signed
          mv app-common-arm64-v8a-*.apk GameHelper-arm64-v8a-release-${{steps.vars.outputs.short_ref}}.apk
          mv app-common-armeabi-v7a-*.apk GameHelper-armeabi-v7a-release-${{steps.vars.outputs.short_ref}}.apk
          mv app-common-universal-*.apk GameHelper-universal-release-${{steps.vars.outputs.short_ref}}.apk
          ls
      
      - name: Create Release
        id: create_release
        if: github.repository == 'vtrayy/GameHelper'
        uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.AGITHUB_TOKEN }}
      
      - name: Upload APK to Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
         token: ${{ secrets.GITHUB_TOKEN }}
         files: 'build/app/signed/**'    
